accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, temp_welcome_view, AccountUpdateView, AccountDeleteView, \
    AccountDetailView

app_name = "accountapp"

urlpatterns = [

    path('temp_welcome/',temp_welcome_view,name='temp_welcome'),

    path('create/',AccountCreateView.as_view(),name='create'),
    path('update/<int:pk>',AccountUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',AccountDeleteView.as_view(),name='delete'),
    path('detail/<int:pk>',AccountDetailView.as_view(),name='detail'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

diamond_goose_mk4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('portfolio/', include('portfolioapp.urls')),
    path('equitymaster/', include('equitymasterapp.urls')),
    path('equitiesowned/', include('equityownedapp.urls')),
    path('equitytransactions/', include('equitytransactionapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = "profileapp" # 추후 함수 활용을 위해서 설정 해줌.

urlpatterns = [
    path('create/',ProfileCreateView.as_view(),name='create'),
    path('update/<int:pk>',ProfileUpdateView.as_view(),name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render

# Create your views here.
from django.template.context_processors import request
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm

has_ownership = [login_required, account_ownership_required]

def temp_welcome_view(request):
    return render(request, 'accountapp/temp_welcome.html')


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:temp_welcome')
    template_name = 'accountapp/create.html'


@method_decorator(has_ownership,'get')
@method_decorator(has_ownership,'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:temp_welcome')
    template_name = 'accountapp/update.html'


@method_decorator(has_ownership,'get')
@method_decorator(has_ownership,'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:temp_welcome')
    template_name = 'accountapp/delete.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

    {% block extrahead %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/accountapp.css' %}">
    {% endblock %}

    <div style="max-width: 500px; margin: 4rem auto">
        <div>
            <h4 class="accountapp_main_title">Sign Up</h4>
        </div>
        <div class="text-white">
            <form action="{% url 'accountapp:create' %}" method="post">
                {% csrf_token %}

                {% bootstrap_form form %}

                <input type="submit" class="btn btn-light col-3">
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

    {% block extrahead %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/accountapp.css' %}">
    {% endblock %}

    <div style="max-width: 500px; margin: 4rem auto">
        <div style="margin: 2rem 0;">
            <h4 class="accountapp_main_title">Delete Account</h4>
            <h6 style="color: #FFFFFF;">Are you sure to delete your account?</h6>
        </div>
        <div class="text-white">
            <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-dark">
                <a href="{% url 'accountapp:detail' pk=target_user.pk %}" class="btn btn-light">취소</a>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

    {% block extrahead %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/accountapp.css' %}">
    {% endblock %}

    <div style="max-width: 500px; margin: 4rem auto">
        <div class="mb-2">
            <h4 class="accountapp_main_title">Account Detail</h4>
        </div>
        <div class="text-white" style="margin-bottom: 1rem;">
            <!-- 여기서의 target_user는 view에서 지정한 context_object_name -->
            {% if target_user.profile %}
            <img src="{{ target_user.profile.image.url }}" alt="Profile Image" style="height: 15rem; border-radius: 1rem; margin-bottom: 1rem;">
            <h2>
                {{ target_user.profile.nickname }}

                {% if target_user == user %}
                    <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                       class="btn btn-info">Edit</a>
                {% endif %}
            </h2>
            <div>
                <h6 style="display: inline">
                    Our honored memeber since
                </h6>
                <p style="display: inline">
                    {{ target_user.date_joined|date:"Y.m.d" }}
                </p>
            </div>
            <div>
                <h6 style="display: inline">
                    And said, "
                </h6>
                <p style="display: inline">
                    {{ target_user.profile.message }}
                </p>
                <h6 style="display: inline">
                    "
                </h6>
            </div>
            {% else %}
                {% if target_user == user %}
                <a href="{% url 'profileapp:create' %}">
                    Create Profile
                </a>
                {% else %}
                <h2 style="color: #FA00BE">
                    Profile 미등록 유저
                </h2>
                {% endif %}
            {% endif %}

        </div>


        {% if target_user == user %}
        <a href="{% url 'accountapp:update' pk=target_user.pk %}">
            <p>
                Change User Info
            </p>
        </a>
        <a href="{% url 'accountapp:delete' pk=target_user.pk %}">
            <p>
                Delete My Account
            </p>
        </a>
        {% endif %}




    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

    {% block extrahead %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/accountapp.css' %}">
    {% endblock %}

    <div style="max-width: 500px; margin: 4rem auto">
        <div class="mb-2">
            <h4 class="accountapp_main_title">Login</h4>
        </div>
        <div class="text-white">
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-light col-3 mt-3">
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/temp_welcome.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

    {% block extrahead %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/accountapp.css' %}">
    {% endblock %}

    <div style="max-width: 500px; margin: 4rem auto">
        <div class="mb-2">
            <h4 class="accountapp_main_title">Welcome</h4>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

    {% block extrahead %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/accountapp.css' %}">
    {% endblock %}

    <div style="max-width: 500px; margin: 4rem auto">
        <div class="mb-2">
            <h4 class="accountapp_main_title">Change User Info</h4>
        </div>
        <div class="text-white">
            <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-light col-3">
            </form>
        </div>
    </div>

{% endblock %}