accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, temp_welcome_view, AccountUpdateView, AccountDeleteView, \
    AccountDetailView

app_name = "accountapp"

urlpatterns = [

    path('temp_welcome/',temp_welcome_view,name='temp_welcome'),

    path('create/',AccountCreateView.as_view(),name='create'),
    path('update/<int:pk>',AccountUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',AccountDeleteView.as_view(),name='delete'),
    path('detail/<int:pk>',AccountDetailView.as_view(),name='detail'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

diamond_goose_mk4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('portfolio/', include('portfolioapp.urls')),
    path('equitymaster/', include('equitymasterapp.urls')),
    path('equitiesowned/', include('equityownedapp.urls')),
    path('equitytransactions/', include('equitytransactionapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equityownedapp/urls.py
from django.urls import path

from equityownedapp.views import EquityOwnedCreateView, EquityOwnedDetailView, EquityOwnedListView

app_name = 'equityownedapp'

urlpatterns = [

    path('create/',EquityOwnedCreateView.as_view(), name='create'),
    path('detail/<int:pk>',EquityOwnedDetailView.as_view(), name='detail'),
    path('list/',EquityOwnedListView.as_view(), name='list'),

]

equitytransactionapp/urls.py
from django.urls import path

from equitytransactionapp.views import EquityTransactionCreateView, EquityTransactionListView, \
    EquityTransactionDeleteView, import_csv, export_csv_template

app_name = 'equitytransactionapp'

urlpatterns = [

    path('create/',EquityTransactionCreateView.as_view(),name='create'),
    path('list/',EquityTransactionListView.as_view(),name='list'),
    path('delete/<int:pk>',EquityTransactionDeleteView.as_view(),name='delete'),

    path('import_csv/', import_csv, name='import_csv'),
    path('export_csv_template/', export_csv_template, name='export_csv_template'),
]

equitytransactionapp/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django import utils

from equityownedapp.models import EquityOwned

TRANSACTION_TYPE_CHOICES = (
    ('BUY', '매수'),
    ('SELL', '매도'),
    ('DIVIDEND', '배당금'),
    ('SPLIT', '액면분할'),
)

class MinValueFloat(models.FloatField):
    def __init__(self, min_value=None, *args, **kwargs):
        self.min_value = min_value
        super(MinValueFloat, self).__init__(*args, **kwargs)

    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value}
        defaults.update(kwargs)
        return super(MinValueFloat, self).formfield(**defaults)

class EquityTransaction(models.Model):
    equity_owned = models.ForeignKey(EquityOwned, on_delete=models.CASCADE, related_name='transaction', null=False)

    transaction_type = models.CharField(max_length=20, choices=TRANSACTION_TYPE_CHOICES, null=False)
    quantity = MinValueFloat(min_value=0.0, null=False)

    # Not-in-use. Substituted by price
    purchase_price = models.FloatField(default=0,null=False)

    price = MinValueFloat(min_value=0.0, default=0, null=False)
    transaction_fee = models.FloatField(default=0)
    transaction_tax = models.FloatField(default=0)
    transaction_date = models.DateTimeField(default=utils.timezone.now, null=False)
    note = models.CharField(max_length=20, default=' -', null=True)

    split_flag = models.BooleanField(default=False)

    creation_date = models.DateTimeField(auto_now=True)
    last_update_date = models.DateTimeField(auto_now_add=True)

equitytransactionapp/forms.py
from django.forms import widgets
from django.forms import ModelForm

from equitytransactionapp.models import EquityTransaction


class EquityTransactionCreationForm(ModelForm):
    class Meta:
        model = EquityTransaction
        fields = ['transaction_type', 'quantity', 'price', 'transaction_fee', 'transaction_tax', 'transaction_date', 'note']

        widgets = {
            'transaction_date': widgets.DateTimeInput(attrs={'type':'date'})
        }

equitytransactionapp/views.py
import csv
import datetime
import os

from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.conf import settings
import pandas as pd

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.timezone import make_aware
from django.views.generic import CreateView, ListView, DeleteView
from django.views.generic.edit import FormMixin

from equityownedapp.models import EquityOwned
from equitytransactionapp.decorator import equity_transaction_ownership_required
from equitytransactionapp.forms import EquityTransactionCreationForm
from equitytransactionapp.models import EquityTransaction

has_ownership = [login_required, equity_transaction_ownership_required]

class EquityTransactionCreateView(CreateView, FormMixin):
    model = EquityTransaction
    form_class = EquityTransactionCreationForm
    template_name = 'equitytransactionapp/create.html'

    def form_valid(self, form):
        temp_transaction = form.save(commit=False)
        temp_transaction.equity_owned = EquityOwned.objects.get(pk=self.request.POST['equity_owned_pk'])
        temp_transaction.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('equityownedapp:detail',kwargs={'pk':self.object.equity_owned.pk})


class EquityTransactionListView(ListView):
    model = EquityTransaction
    context_object_name = 'equity_transaction_list'
    template_name = 'equitytransactionapp/list.html'


class EquityTransactionDeleteView(DeleteView):
    model = EquityTransaction
    context_object_name = 'target_equity_transaction'
    template_name = 'equitytransactionapp/delete.html'

    def get_success_url(self):
        return reverse('equityownedapp:detail',kwargs={'pk':self.object.equity_owned.pk})


def import_csv(request):
    equity_owned_pk = request.POST['equity_owned_pk']

    try:
        if request.method == 'POST' and request.FILES['transaction_file']:

            transaction_file = request.FILES['transaction_file']
            save_dir = os.path.join(settings.MEDIA_ROOT, 'equity_transaction_csv')
            fs = FileSystemStorage(location=save_dir)
            file_name = fs.save(transaction_file.name, transaction_file)
            new_dir = 'equity_transaction_csv/' + file_name
            uploaded_file_url = fs.url(new_dir)
            excel_file = uploaded_file_url
            excel_transaction_data = pd.read_csv("."+excel_file, encoding='utf-8')
            db_frame = excel_transaction_data

            for db_frame in db_frame.itertuples():

                # transaction_date input data make_aware
                naive_datetime = datetime.datetime.strptime(db_frame.transaction_date, "%Y-%m-%d %H:%M:%S")
                aware_datetime = make_aware(naive_datetime)

                obj = EquityTransaction.objects.create(
                    equity_owned=EquityOwned.objects.get(pk=equity_owned_pk),
                    transaction_type=db_frame.transaction_type,
                    quantity=db_frame.quantity,
                    price=db_frame.price,
                    transaction_fee=db_frame.transaction_fee,
                    transaction_tax=db_frame.transaction_tax,
                    transaction_date=aware_datetime,
                    note=db_frame.note
                )

                obj.save()

            return HttpResponseRedirect(reverse('equityownedapp:detail', kwargs={'pk':equity_owned_pk}))
    except Exception as identifier:
        print(identifier)

    return render(request, 'equityownedapp/detail.html', {'pk': equity_owned_pk})


def export_csv_template(request):
    if request.method == 'POST':
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="transaction_csv_template.csv"'
        writer = csv.writer(response)
        # Column Insert
        writer.writerow([
            'transaction_type',
            'quantity',
            'price',
            'transaction_fee',
            'transaction_tax',
            'transaction_date',
            'note',
        ])
        # Sample Line Insert
        writer.writerow([
            'BUY',
            '1',
            '100',
            '1',
            '2',
            '1993-04-27 04:00:00',
            'Sample Format',
        ])

        return response

    return render(request,'equityownedapp/detail.html')

equitytransactionapp/templates/equitytransactionapp/create.html
{% load bootstrap4 %}

<div style="margin-bottom: .5rem; background-color: #264257; color: #FFFFFF;">
    <div style="display: block; width: 100%; background-color: #007D8A;">
        <div>
            <h5 style="margin-left: 1rem; color: #FFFFFF;">Add Transaction</h5>
        </div>
    </div>
    <div style="display: block; width: 80%; margin-left: 1rem; background-color: #264257;">
        <form action="{% url 'equitytransactionapp:create' %}" method="post" style="">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% if user.is_authenticated %}
                <input type="submit" class="btn btn-warning btn-sm">
            {% else %}
                <a href="{% url 'accountapp:login' %}?next={{ request.path }}"></a>
            {% endif %}
            <input type="hidden" name="equity_owned_pk" value="{{ equity_owned.pk }}">
        </form>
    </div>
</div>

equitytransactionapp/templates/equitytransactionapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load currency_format %}

{% block content %}

    {% load static %}
    {% block extrahead %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/equityapp.css' %}">
    {% endblock %}

    <div style="max-width: 500px; margin: 4rem auto">
        <div style="margin: 2rem 0;">
            <h4 class="equityapp_main_title">Delete Transaction</h4>
            <h6 style="color: #FFFFFF;">Are you sure to delete this transaction?</h6>
            <div style="display: block; min-height: 5rem; background-color: #264257;">
                <table class="equityapp_inverted_table">
                    <tr class="equityapp_inverted_table_tr">
                        <th class="equityapp_inverted_table_th_td">거래일자</th>
                        <th class="equityapp_inverted_table_th_td">유형</th>
                        <th class="equityapp_inverted_table_th_td">수량</th>
                        <th class="equityapp_inverted_table_th_td">가격</th>
                        <th class="equityapp_inverted_table_th_td">제비용</th>
                        <th class="equityapp_inverted_table_th_td">제세금</th>
                        <th class="equityapp_inverted_table_th_td">비고</th>
                    </tr>
                        <tr class="equityapp_inverted_table_tr">
                            <td class="equityapp_inverted_table_th_td">{{ target_equity_transaction.transaction_date|date:"Y.m.d h:i:s" }}</td>
                            <td class="equityapp_inverted_table_th_td">{{ target_equity_transaction.transaction_type }}</td>
                            <td class="equityapp_inverted_table_th_td">{{ target_equity_transaction.quantity }}</td>

                            {% load currency_format %}
                            {% if transaction.equity_owned.equity.currency == 'USD' %}}
                                <td class="equityapp_inverted_table_th_td">{{ target_equity_transaction.price|currency_usd }}</td>
                                <td class="equityapp_inverted_table_th_td">{{ target_equity_transaction.transaction_fee|currency_usd  }}</td>
                                <td class="equityapp_inverted_table_th_td">{{ target_equity_transaction.transaction_tax|currency_usd  }}</td>
                            {% elif transaction.equity_owned.equity.currency == 'KRW' %}}
                                <td class="equityapp_inverted_table_th_td">{{ target_equity_transaction.price|currency_krw }}</td>
                                <td class="equityapp_inverted_table_th_td">{{ target_equity_transaction.transaction_fee|currency_krw  }}</td>
                                <td class="equityapp_inverted_table_th_td">{{ target_equity_transaction.transaction_tax|currency_krw  }}</td>
                            {% else %}
                                <td class="equityapp_inverted_table_th_td">{{ target_equity_transaction.price|floatformat:2|intcomma }}</td>
                                <td class="equityapp_inverted_table_th_td">{{ target_equity_transaction.transaction_fee|floatformat:2|intcomma  }}</td>
                                <td class="equityapp_inverted_table_th_td">{{ target_equity_transaction.transaction_tax|floatformat:2|intcomma  }}</td>
                            {% endif %}

                            {% if transaction.note %}
                                <td class="equityapp_inverted_table_th_td">{{ target_equity_transaction.note }}</td>
                            {% else %}
                                <td class="equityapp_inverted_table_th_td"></td>
                            {% endif %}
                        </tr>
                </table>
            </div>
        </div>
        <div class="text-white">
            <form action="{% url 'equitytransactionapp:delete' pk=target_equity_transaction.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-dark">
                <a href="{% url 'equityownedapp:detail' pk=target_equity_transaction.equity_owned.pk %}" class="btn btn-light">취소</a>
            </form>
        </div>
    </div>

{% endblock %}

equitytransactionapp/templates/equitytransactionapp/export_csv_template.html
{% load bootstrap4 %}

<div style="display: inline-block; float: right; ">
    <form action="{% url 'equitytransactionapp:export_csv_template' %}"  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button type="submit" class="btn btn-info btn-sm btn-block" >CSV Template</button>
    </form>
</div>

equitytransactionapp/templates/equitytransactionapp/import_csv.html
{% load bootstrap4 %}

<div style="margin-bottom: 1rem; background-color: #264257; color: #FFFFFF;">
    <div style="display: inline-block; width: 100%; background-color: #007D8A;">
        <div style="display: inline-block; float: left;">
            <h5 style="margin-left: 1rem; color: #FFFFFF;">CSV Mass Upload</h5>
        </div>
    </div>
    <div style="display: block; width: 80%; margin-left: 1rem; background-color: #264257;">
        <form action="{% url 'equitytransactionapp:import_csv' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="x_content">
                <div class="col-md-8 col-sm-12 col-xs-12 form-group">
                    </label>
                </div>
                <input type="file" name="transaction_file" class="form-control">
                <input type="hidden" name="equity_owned_pk" value="{{ equity_owned.pk }}">
                <button type="submit" class="btn btn-warning btn-sm" >Upload</button>

                <br/>
            </div>
        </form>
    </div>
</div>

equitytransactionapp/templates/equitytransactionapp/list.html
{% load static %}
{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/equityapp.css' %}">
{% endblock %}

<div>
    <div style="display: block; width: 100%; ">
        <h4 style="margin-left: 1rem; color: #FFFFFF;">Records</h4>
    </div>

    <div style="display: block; margin-left: 1%;">
        <table style="width: 100%; color: #FFFFFF;">
            <tr>
                <th class="transaction_record_table_th_10p">거래일자</th>
                <th class="transaction_record_table_th_5p">유형</th>
                <th class="transaction_record_table_th_5p">수량</th>
                <th class="transaction_record_table_th_10p">가격</th>
                <th class="transaction_record_table_th_5p">제비용</th>
                <th class="transaction_record_table_th_5p">제세금</th>
                <th class="transaction_record_table_node_th">비고</th>
                <th class="transaction_record_table_delete_th">삭제</th>
            </tr>
            {% for transaction in equity_owned.transaction.all|dictsortreversed:"transaction_date" %}
                    <tr>
                        <td class="transaction_record_table_td_10p">{{ transaction.transaction_date|date:"Y-m-d h:i:s" }}</td>
                        <td class="transaction_record_table_td_5p">{{ transaction.transaction_type }}</td>
                        <td class="transaction_record_table_td_5p">{{ transaction.quantity }}</td>

                        {% load currency_format %}
                        {% if transaction.equity_owned.equity.currency == 'USD' %}
                            <td class="transaction_record_table_td_10p">{{ transaction.price|currency_usd }}</td>
                            <td class="transaction_record_table_td_5p">{{ transaction.transaction_fee|currency_usd  }}</td>
                            <td class="transaction_record_table_td_5p">{{ transaction.transaction_tax|currency_usd  }}</td>
                        {% elif transaction.equity_owned.equity.currency == 'KRW' %}
                            <td class="transaction_record_table_td_10p">{{ transaction.price|currency_krw }}</td>
                            <td class="transaction_record_table_td_5p">{{ transaction.transaction_fee|currency_krw  }}</td>
                            <td class="transaction_record_table_td_5p">{{ transaction.transaction_tax|currency_krw  }}</td>
                        {% else %}
                            <td class="transaction_record_table_td_10p">{{ transaction.price|floatformat:2|intcomma }}</td>
                            <td class="transaction_record_table_td_5p">{{ transaction.transaction_fee|floatformat:2|intcomma  }}</td>
                            <td class="transaction_record_table_td_5p">{{ transaction.transaction_tax|floatformat:2|intcomma  }}</td>
                        {% endif %}

                        {% if transaction.note %}
                            <td class="transaction_record_table_node_td">{{ transaction.note }}</td>
                        {% else %}
                            <td class="transaction_record_table_node_td"></td>
                        {% endif %}

                        {% if transaction.equity_owned.owner == user %}
                            <td class="transaction_record_table_delete_td">
                                <a href="{% url 'equitytransactionapp:delete' pk=transaction.pk %}"
                                   style="color: #FA0067;text-decoration: none;">X</a>
                            </td>
                        {% else %}
                            <td class="transaction_record_table_delete_td"></td>
                        {% endif %}
                    </tr>
            {% endfor %}
        </table>
    </div>
</div>