accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, temp_welcome_view, AccountUpdateView, AccountDeleteView, \
    AccountDetailView

app_name = "accountapp"

urlpatterns = [

    path('temp_welcome/',temp_welcome_view,name='temp_welcome'),

    path('create/',AccountCreateView.as_view(),name='create'),
    path('update/<int:pk>',AccountUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',AccountDeleteView.as_view(),name='delete'),
    path('detail/<int:pk>',AccountDetailView.as_view(),name='detail'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

articleapp/urls.py
from django.urls import path

from articleapp.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView

app_name = 'articleapp'

urlpatterns = [

    path('list/', ArticleListView.as_view(), name='list'),
    path('create/',ArticleCreateView.as_view(),name='create'),
    path('detail/<int:pk>',ArticleDetailView.as_view(),name='detail'),
    path('update/<int:pk>',ArticleUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',ArticleDeleteView.as_view(),name='delete'),

]

diamond_goose_mk4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('portfolio/', include('portfolioapp.urls')),
    path('equitymaster/', include('equitymasterapp.urls')),
    path('equitiesowned/', include('equityownedapp.urls')),
    path('equitytransactions/', include('equitytransactionapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equityownedapp/urls.py
from django.urls import path

from equityownedapp.views import EquityOwnedCreateView, EquityOwnedDetailView, EquityOwnedListView

app_name = 'equityownedapp'

urlpatterns = [

    path('create/',EquityOwnedCreateView.as_view(), name='create'),
    path('detail/<int:pk>',EquityOwnedDetailView.as_view(), name='detail'),
    path('list/',EquityOwnedListView.as_view(), name='list'),

]

portfolioapp/urls.py
from django.urls import path

from portfolioapp.views import PortfolioCreateView, PortfolioDetailView

app_name = 'portfolioapp'

urlpatterns = [

    path('create/',PortfolioCreateView.as_view(), name='create'),
    path('detail/<int:pk>',PortfolioDetailView.as_view(), name='detail'),

]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="background-color: #081321; font-family: NanumSquareR">

    {% include 'header.html' %}
    <hr style="color: #FFFFFF">
    {% block content %}
    {% endblock %}
    <hr style="color: #FFFFFF">
    {% include 'footer.html' %}


</body>
</html>

templates/footer.html
<div class="diamond_goose_footer">
    <div class="diamond_goose_footer_button">
        <span>About This</span> |
        <span>Notice</span> |
        <span>Contact</span>
    </div>
    <div style="margin-top : 1rem; ">
        <h6 class="diamond_goose_footer_logo">Diamond Goose MK2</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit-no">
    <title>Title</title>

    <!--  Bootstrap Link  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!--  Google Fonts  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@700&display=swap" rel="stylesheet">

    <!--  Default CSS Link  -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">

    <!-- 자식 css 적용을 위한 block-->
    {% block extrahead %}
    {% endblock %}

    <!-- 다운로드 받아서 static.fonts 에 저장한 폰트들 등록 -->
    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR',
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB',
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL',
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>

    <img src="{% static 'images/diamond_goose_logo_mk1.png' %}" alt="Logo Image"
         style="width: 130px; float: left; margin-left:2rem; margin-right: 1.5rem;">

</head>

templates/header.html
<div class="diamond_goose_header" style="text-align:left;" >
    <div>
        <div>
            <h1 style="font-size: 3rem;">Diamond Goose MK2</h1>
        </div>

        <div style="font-size: 1.5rem;">
            <a href="{% url 'accountapp:temp_welcome' %}" class="link-info" style="text-decoration-line: none;">
                <span>Temp Welcome</span>
            </a> |

            {% if user.portfolio %}
                <a href="{% url 'portfolioapp:detail' pk=user.pk %}" class="link-info" style="text-decoration-line: none;">
                    <span>My Portfolio</span>
                </a> |
            {% else %}
                <a href="{% url 'portfolioapp:create' %}" class="link-info" style="text-decoration-line: none;">
                    <span>Open Portfolio</span>
                </a> |
            {% endif %}


            <a href="{% url 'equityownedapp:list' %}" class="link-info" style="text-decoration-line: none;">
                <span>My Equities</span>
            </a> |
            <a href="{% url 'articleapp:list' %}" class="link-info" style="text-decoration-line: none;">
                <span>Articles</span>
            </a> |

            {% if user.is_authenticated %}
                <a href="{% url 'accountapp:detail' pk=user.pk %}" class="link-info" style="text-decoration-line: none;">
                    <span>My Page</span>
                </a> |
                <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="link-info" style="text-decoration-line: none;">
                    <span>Logout</span>
                </a>
            {% else %}
                <a href="{% url 'accountapp:create' %}" class="link-info" style="text-decoration-line: none;">
                    <span>Sign Up</span>
                </a> |
                <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="link-info" style="text-decoration-line: none;">
                    <span>Login</span>
                </a>
            {% endif %}
        </div>
    </div>
</div>