accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, temp_welcome_view, AccountUpdateView, AccountDeleteView, \
    AccountDetailView

app_name = "accountapp"

urlpatterns = [

    path('temp_welcome/',temp_welcome_view,name='temp_welcome'),

    path('create/',AccountCreateView.as_view(),name='create'),
    path('update/<int:pk>',AccountUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',AccountDeleteView.as_view(),name='delete'),
    path('detail/<int:pk>',AccountDetailView.as_view(),name='detail'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

articleapp/urls.py
from django.urls import path

from articleapp.views import ArticleCreateView, ArticleListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView

app_name = 'articleapp'

urlpatterns = [

    path('list/', ArticleListView.as_view(), name='list'),
    path('create/',ArticleCreateView.as_view(),name='create'),
    path('detail/<int:pk>',ArticleDetailView.as_view(),name='detail'),
    path('update/<int:pk>',ArticleUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',ArticleDeleteView.as_view(),name='delete'),

]

diamond_goose_mk4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('portfolio/', include('portfolioapp.urls')),
    path('equitymaster/', include('equitymasterapp.urls')),
    path('equitiesowned/', include('equityownedapp.urls')),
    path('equitytransactions/', include('equitytransactionapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Article(models.Model):
    owner = models.ForeignKey(User,on_delete=models.SET_NULL, related_name='article',null=True)

    title = models.CharField(max_length=200, null=False)
    image = models.ImageField(upload_to='articles/', null=False)
    content = models.TextField(null=True)

    creation_date = models.DateTimeField(auto_now=True)
    last_update_date = models.DateTimeField(auto_now_add=True)

articleapp/forms.py
from django.forms import ModelForm

from articleapp.models import Article


class ArticleCreationForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'image', 'content']

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article
from commentapp.forms import CommentCreationForm

has_ownership = [login_required, article_ownership_required]


class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 25


@method_decorator(login_required,'get')
@method_decorator(login_required,'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        temp_article = form.save(commit=False)
        temp_article.owner = self.request.user
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail',kwargs={'pk':self.object.pk})


@method_decorator(login_required,'get')
class ArticleDetailView(DetailView, FormMixin):
    model = Article
    form_class = CommentCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'


@method_decorator(has_ownership,'get')
@method_decorator(has_ownership,'post')
class ArticleUpdateView(UpdateView):
    model = Article
    form = ArticleCreationForm
    fields = ['title', 'image', 'content']
    context_object_name = 'target_article'
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail',kwargs={'pk':self.object.pk})


@method_decorator(has_ownership,'get')
@method_decorator(has_ownership,'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    template_name = 'articleapp/delete.html'
    success_url = reverse_lazy('articleapp:list')

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

    {% block extrahead %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/articleapp.css' %}">
    {% endblock %}

    <div style="max-width: 500px; margin: 4rem auto">
        <div class="mb-2">
            <h4 class="articleapp_main_title">Create Article</h4>
        </div>
        <div class="text-white">
            <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-light col-3">
            </form>
        </div>
    </div>

{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

    {% block extrahead %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/articleapp.css' %}">
    {% endblock %}

    <div style="max-width: 500px; margin: 4rem auto">
        <div style="margin: 2rem 0;">
            <h4 class="articleapp_main_title">Delete Article</h4>
            <h6 style="color: #FFFFFF;">Are you sure to delete your article?</h6>
        </div>
        <div class="text-white">
            <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-dark">
                <a href="{% url 'articleapp:detail' pk=target_article.pk %}" class="btn btn-light">취소</a>
            </form>
        </div>
    </div>

{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <style>
        .article_title {
            height: 2.5rem;
            color: #FFFFFF;
            margin-bottom: 2rem;
        }
    </style>

    <div style="margin: 2rem 2rem">
        <div style="margin: 1rem auto;">
            {% if target_article.owner == user %}
                <a href="{% url 'articleapp:update' pk=target_article.pk %}" class="btn btn-light" style="display: inline">수정하기</a>
                <a href="{% url 'articleapp:delete' pk=target_article.pk %}" class="btn btn-light" style="display: inline">삭제하기</a>
            {% endif %}
            <a href="{% url 'articleapp:list' %}" class="btn btn-light" style="display: inline">글 목록</a>
        </div>
        <div style="display: inline-block; margin: 1rem auto;">
            <h1 class="article_title">
                {{ target_article.title }}
            </h1>
        </div>
        <div style="margin: .5rem 1rem; color: #FFFFFF;">
            <h6>
                written by
                <a href="{% url 'accountapp:detail' pk=target_article.owner.pk %}"
                   style="margin-left: 0.3rem; color:#79F92D; font-size: 1.2rem;">
                    {{ target_article.owner.profile.nickname }}
                </a>
            </h6>
            <h6 style="color: #FFFFFF">
                {{ target_article.creation_date }}
            </h6>
        </div>
        <div style="display: inline-block; margin-top: 2rem; min-height: 10rem;">
            <div style="display: inline-block; max-width: 50%; float:left; margin-right: 1.5rem; margin-bottom: 1rem;">
                <img src="{{ target_article.image.url }}" alt=""
                     style="max-width: 100%;">
            </div>
            <div style="display: inline-block; color: #FFFFFF;">
                <p style="line-height: 2; font-size: 1.1rem;">{{ target_article.content|linebreaks }}</p>
            </div>
        </div>
    </div>

    <div>
        {% include 'commentapp/detail.html' with article=target_article %}
        {% include 'commentapp/create.html' with article=target_article %}
    </div>

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% block extrahead %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/articleapp.css' %}">
    {% endblock %}

    <div style="width:100%; text-align: center;">
        <a href="{% url 'articleapp:create' %}" class="btn btn-light col-2" style="margin: 3rem 0;" >집필하기</a>
    </div>

    <div class="container">
        {% if article_list %}
            {% for article in article_list %}
                <div>
                    <a href="{% url 'articleapp:detail' pk=article.pk %}" style="text-decoration-line: none;">
                        {% include 'snippets/article_card.html' with article=article %}
                    </a>
                </div>
            {% endfor %}
        {% else %}
            <div>
                <h4>No article yet... Please tell us your ideas.</h4>
            </div>
        {% endif %}
    </div>

    {% include 'snippets/article_pagination.html' with page_obj=page_obj %}

    <script src="{% static 'js/magicgrid.js' %}"></script>

{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}

    {% block extrahead %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/articleapp.css' %}">
    {% endblock %}

    <div style="max-width: 500px; margin: 4rem auto">
        <div class="mb-2">
            <h4 class="articleapp_main_title">Edit Article</h4>
        </div>
        <div class="text-white">
            <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-light col-3">
            </form>
        </div>
    </div>

{% endblock %}